### ISSUE TITLE
EditElement has no option for "value_in_text_value" (problem in java app)

### ISSUE THREAD

**Issue by KaterinaCZ** [ultimaterpa/urpaform#19]
In java app is value in text_value (not in value, not in name). Urpaform cannot check if value is filled in such case.

**Comment by Slavaqq** [comment]
I rename the argument `value_in_text` to `value_is_in`. Default is set to `"value"` and other options are `"name"` or `"text_value"`. The problem with the `text_value` method is that it returns the string filled in the form plus the line breaker `"\n"`.

**Comment by Slavaqq** [comment]
This issue was solved.
